version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: jenkins
      DB_USERNAME: root
      DB_PASSWORD: devmbilal
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: http://localhost

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: devmbilal
      MYSQL_DATABASE: jenkins
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
